name: Build and deploy changes

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@4

            - name: Welcome message
              run: echo "Hello the pipeline is running"
            
            - name: List files
              run: ls

            - name: Read file
              run: cat README.md