name: Build and deploy changes

on: push

jobs:
  checkout_repo:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome message
        run: echo "Hello the pipeline is running"
  build_and_push:
    needs: checkout_repo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
      - name: List files
        run: ls -latr
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx for M4 Mac architecture
        env:
          PLATFORM_NAME: linux/amd64
          DOCKER_USERNAME: boitenoire
          IMAGE_NAME: learning-app-ecommerce
        run: docker buildx build --platform $PLATFORM_NAME -t $DOCKER_USERNAME/$IMAGE_NAME:latest . --push
      - name: Docker Publish
        env:
          CONTAINER_REGISTRY: docker.io
          DOCKER_USERNAME: boitenoire
          IMAGE_NAME: learning-app-ecommerce
        run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
